### ISSUE TITLE
Initial stuff

### ISSUE THREAD

**Issue by jblazek** [jblazek/todolist#1]
## Tasks

* [x] Add hello world functionality
* [x] Add build and test scaffolding
* [x] Add dockerfile
* [ ] Add prepare release script to make docker image
* [ ] Add make release script to push docker image
* [ ] Add run script to build test and run image
* [ ] Add API logic using EF Core
* [ ] Add API logic using MQ
